// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqewamsbifugrevmoiqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZXdhbXNiaWZ1Z3Jldm1vaXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MzQ0NjksImV4cCI6MjA2ODExMDQ2OX0.CJOgtvajQ9Q4YAf2RmLm3yySebYBSSZIUHNBRcMpHUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});